name: drift_postgis
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  dart_jts: ^0.3.0+1
  drift: ^2.15.0
  drift_postgres: ^1.1.0
  postgres: ^3.1.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.17.0
  lints: ^2.1.0
  test: ^1.24.0
