name: geo_city
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  dart_jts: ^0.3.0+1
  drift: ^2.15.0
  drift_postgis:
    path: ../../
  drift_postgres: ^1.1.0
  postgres: ^3.1.0

  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  drift_dev: ^2.17.0
  lints: ^2.1.0
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0